- name: Install boto3 and botocore
  ansible.builtin.import_tasks:
    file: boto.yml

- name: Copy MongoDB repo
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: Update MongoDB bind address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable and Start MongoDB
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    state: restarted