- name: Setup Catalogue component
  hosts: all
  become: true
  vars:
    component: catalogue
  tasks:
    - name: Load NodeJS
      ansible.builtin.include_tasks:
        file: nodejs.yml


  nodejs() {
  echo -e "${color} Configuring NodeJS Repos ${nocolor}"
  curl -sL https://rpm.nodesource.com/setup_lts.x | bash  &>>$log_file
  stat_check $?

  echo -e "${color} Install NodeJS${nocolor}"
  yum install nodejs -y  &>>$log_file
  stat_check $?

  app_presetup

  echo -e "${color} Install NodeJS Dependencies${nocolor}"
  npm install  &>>$log_file
  stat_check $?

  systemd_setup
}
