- name: Configure Erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh ; curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Install RabbitMQ Server
  ansible.builtin.yum:
    name: rabbit-mq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-serve
    enabled: yes
    state: restarted

- name: Add Roboshop user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present


