
#echo -e " ${color}  Setup MySQL Password  ${nocolor} "
#mysql_secure_installation --set-root-pass $1 &>>/tmp/roboshop.log
#stat_check $?

- name: Disable MySQL Default Version
  ansible.builtin.shell: yum module disable mysql -y

- name: Copy MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
    remote_rc: yes

- name: Install MySQL Community Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes
    state: restarted

- name: Setup Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

