- name: Install boto3 and botocore
  ansible.builtin.import_role:
    name: common
    tasks_from: boto

- name: Load NodeJS
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Copy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.roboshop.blog </app/db/master-data.js






# - name: load schema
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: mongo_schema_setup
