---
# Mongo Schema Setup

- name: Copy MongoDB repo file
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: present


- name: Load MongoDB schema
  shell: >
    mongo --host mongodb-dev.roboshop.blog
    < /app/schema/{{ component }}.js
  args:
    executable: /bin/bash